#!/usr/bin/php
<?php

# Copyright 2019 Mobimentum Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require_once(dirname(__FILE__) . '/hooks-config.php');
require_once(dirname(__FILE__) . '/hooks-lib.php');

print "### HOOK PATCHSET-CREATED START " . __FILE__ . "\n";

if (IS_GERRIT && !isset($opts['recheck'])) {
	// FIXME Wait for sync to happen
	print "Waiting for sync...\n";
	sleep(5);
}

// Check required params
$paramsOk = TRUE;
if (empty($config['url'])) $paramsOk = missingParam('gitlab-config', 'url');
if (empty($config['gerritUser'])) $paramsOk = missingParam('gitlab-config', 'gerritUser');
if (empty($opts['project'])) $paramsOk = missingParam('param', 'project');
if (empty($opts['branch'])) $paramsOk = missingParam('param', 'branch');
if (empty($opts['change-url'])) $paramsOk = missingParam('param', 'change-url');
if (empty($opts['commit'])) $paramsOk = missingParam('param', 'commit');
if (empty($opts['patchset'])) $paramsOk = missingParam('param', 'patchset');

if ($paramsOk) {
	// Get project ID from project name 
	$projectId = getProjectId($opts['project']);
	$headers = ["Content-Type: application/x-www-form-urlencoded", "Private-Token: " . $config['token']];
	$merge_request_api = $config['url'] . "/api/v4/projects/{$projectId}/merge_requests";

	if ($projectId) {
		$source_branch = getBranchName($opts['change-url'], $opts['patchset']);
		print "Project ID: $projectId, branch: {$opts['branch']}, ref: {$source_branch}\n";
		$postdata = http_build_query([
			'id' => $projectId,
			'source_branch' => $source_branch,
			'target_branch' => $opts['branch'],
			'title' => $opts['change-url']
		]);
		list($headers, $body, $code) = doRequest($merge_request_api, $postdata, $headers);
		print "Got response: $code\n";
	}
	else print "Project {$opts['project']} NOT FOUND!\n";
}

print "### HOOK PATCHSET-CREATED END\n\n";

?>
